// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: vote_submit_message.proto

package vote_submit_message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainVoteSubmitService_SubmitVote_FullMethodName = "/vote_submit_message.BlockchainVoteSubmitService/SubmitVote"
)

// BlockchainVoteSubmitServiceClient is the client API for BlockchainVoteSubmitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainVoteSubmitServiceClient interface {
	SubmitVote(ctx context.Context, in *VoteSubmitRequest, opts ...grpc.CallOption) (*VoteSubmitResponse, error)
}

type blockchainVoteSubmitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainVoteSubmitServiceClient(cc grpc.ClientConnInterface) BlockchainVoteSubmitServiceClient {
	return &blockchainVoteSubmitServiceClient{cc}
}

func (c *blockchainVoteSubmitServiceClient) SubmitVote(ctx context.Context, in *VoteSubmitRequest, opts ...grpc.CallOption) (*VoteSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteSubmitResponse)
	err := c.cc.Invoke(ctx, BlockchainVoteSubmitService_SubmitVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainVoteSubmitServiceServer is the server API for BlockchainVoteSubmitService service.
// All implementations must embed UnimplementedBlockchainVoteSubmitServiceServer
// for forward compatibility.
type BlockchainVoteSubmitServiceServer interface {
	SubmitVote(context.Context, *VoteSubmitRequest) (*VoteSubmitResponse, error)
	mustEmbedUnimplementedBlockchainVoteSubmitServiceServer()
}

// UnimplementedBlockchainVoteSubmitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainVoteSubmitServiceServer struct{}

func (UnimplementedBlockchainVoteSubmitServiceServer) SubmitVote(context.Context, *VoteSubmitRequest) (*VoteSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVote not implemented")
}
func (UnimplementedBlockchainVoteSubmitServiceServer) mustEmbedUnimplementedBlockchainVoteSubmitServiceServer() {
}
func (UnimplementedBlockchainVoteSubmitServiceServer) testEmbeddedByValue() {}

// UnsafeBlockchainVoteSubmitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainVoteSubmitServiceServer will
// result in compilation errors.
type UnsafeBlockchainVoteSubmitServiceServer interface {
	mustEmbedUnimplementedBlockchainVoteSubmitServiceServer()
}

func RegisterBlockchainVoteSubmitServiceServer(s grpc.ServiceRegistrar, srv BlockchainVoteSubmitServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockchainVoteSubmitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainVoteSubmitService_ServiceDesc, srv)
}

func _BlockchainVoteSubmitService_SubmitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainVoteSubmitServiceServer).SubmitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainVoteSubmitService_SubmitVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainVoteSubmitServiceServer).SubmitVote(ctx, req.(*VoteSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainVoteSubmitService_ServiceDesc is the grpc.ServiceDesc for BlockchainVoteSubmitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainVoteSubmitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vote_submit_message.BlockchainVoteSubmitService",
	HandlerType: (*BlockchainVoteSubmitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVote",
			Handler:    _BlockchainVoteSubmitService_SubmitVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote_submit_message.proto",
}
