// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: vote_submit_message.proto

package vote_submit_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitBallotTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHash      string                 `protobuf:"bytes,1,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	Option        string                 `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBallotTransactionRequest) Reset() {
	*x = SubmitBallotTransactionRequest{}
	mi := &file_vote_submit_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBallotTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBallotTransactionRequest) ProtoMessage() {}

func (x *SubmitBallotTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_submit_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBallotTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitBallotTransactionRequest) Descriptor() ([]byte, []int) {
	return file_vote_submit_message_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitBallotTransactionRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *SubmitBallotTransactionRequest) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *SubmitBallotTransactionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SubmitBallotTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteHash      string                 `protobuf:"bytes,2,opt,name=vote_hash,json=voteHash,proto3" json:"vote_hash,omitempty"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBallotTransactionResponse) Reset() {
	*x = SubmitBallotTransactionResponse{}
	mi := &file_vote_submit_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBallotTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBallotTransactionResponse) ProtoMessage() {}

func (x *SubmitBallotTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_submit_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBallotTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitBallotTransactionResponse) Descriptor() ([]byte, []int) {
	return file_vote_submit_message_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitBallotTransactionResponse) GetVoteHash() string {
	if x != nil {
		return x.VoteHash
	}
	return ""
}

func (x *SubmitBallotTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitBallotTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_vote_submit_message_proto protoreflect.FileDescriptor

const file_vote_submit_message_proto_rawDesc = "" +
	"\n" +
	"\x19vote_submit_message.proto\x12\x13vote_submit_message\"k\n" +
	"\x1eSubmitBallotTransactionRequest\x12\x1b\n" +
	"\tuser_hash\x18\x01 \x01(\tR\buserHash\x12\x16\n" +
	"\x06option\x18\x02 \x01(\tR\x06option\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"p\n" +
	"\x1fSubmitBallotTransactionResponse\x12\x1b\n" +
	"\tvote_hash\x18\x02 \x01(\tR\bvoteHash\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xa4\x01\n" +
	"\x1bBlockchainVoteSubmitService\x12\x84\x01\n" +
	"\x17SubmitBallotTransaction\x123.vote_submit_message.SubmitBallotTransactionRequest\x1a4.vote_submit_message.SubmitBallotTransactionResponseB%Z#../network/gRPC/vote_submit_messageb\x06proto3"

var (
	file_vote_submit_message_proto_rawDescOnce sync.Once
	file_vote_submit_message_proto_rawDescData []byte
)

func file_vote_submit_message_proto_rawDescGZIP() []byte {
	file_vote_submit_message_proto_rawDescOnce.Do(func() {
		file_vote_submit_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_submit_message_proto_rawDesc), len(file_vote_submit_message_proto_rawDesc)))
	})
	return file_vote_submit_message_proto_rawDescData
}

var file_vote_submit_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vote_submit_message_proto_goTypes = []any{
	(*SubmitBallotTransactionRequest)(nil),  // 0: vote_submit_message.SubmitBallotTransactionRequest
	(*SubmitBallotTransactionResponse)(nil), // 1: vote_submit_message.SubmitBallotTransactionResponse
}
var file_vote_submit_message_proto_depIdxs = []int32{
	0, // 0: vote_submit_message.BlockchainVoteSubmitService.SubmitBallotTransaction:input_type -> vote_submit_message.SubmitBallotTransactionRequest
	1, // 1: vote_submit_message.BlockchainVoteSubmitService.SubmitBallotTransaction:output_type -> vote_submit_message.SubmitBallotTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vote_submit_message_proto_init() }
func file_vote_submit_message_proto_init() {
	if File_vote_submit_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_submit_message_proto_rawDesc), len(file_vote_submit_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_submit_message_proto_goTypes,
		DependencyIndexes: file_vote_submit_message_proto_depIdxs,
		MessageInfos:      file_vote_submit_message_proto_msgTypes,
	}.Build()
	File_vote_submit_message_proto = out.File
	file_vote_submit_message_proto_goTypes = nil
	file_vote_submit_message_proto_depIdxs = nil
}
