// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: vote_message.proto

package vote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteHash      string                 `protobuf:"bytes,1,opt,name=vote_hash,json=voteHash,proto3" json:"vote_hash,omitempty"`
	VoteOption    string                 `protobuf:"bytes,2,opt,name=vote_option,json=voteOption,proto3" json:"vote_option,omitempty"`
	ElectionId    string                 `protobuf:"bytes,3,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_vote_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_vote_message_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequest) GetVoteHash() string {
	if x != nil {
		return x.VoteHash
	}
	return ""
}

func (x *VoteRequest) GetVoteOption() string {
	if x != nil {
		return x.VoteOption
	}
	return ""
}

func (x *VoteRequest) GetElectionId() string {
	if x != nil {
		return x.ElectionId
	}
	return ""
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   int64                  `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_vote_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_vote_message_proto_rawDescGZIP(), []int{1}
}

func (x *VoteResponse) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

var File_vote_message_proto protoreflect.FileDescriptor

const file_vote_message_proto_rawDesc = "" +
	"\n" +
	"\x12vote_message.proto\x12\x04vote\"l\n" +
	"\vVoteRequest\x12\x1b\n" +
	"\tvote_hash\x18\x01 \x01(\tR\bvoteHash\x12\x1f\n" +
	"\vvote_option\x18\x02 \x01(\tR\n" +
	"voteOption\x12\x1f\n" +
	"\velection_id\x18\x03 \x01(\tR\n" +
	"electionId\"1\n" +
	"\fVoteResponse\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x03R\vblockHeight2H\n" +
	"\x11BlockchainService\x123\n" +
	"\n" +
	"SubmitVote\x12\x11.vote.VoteRequest\x1a\x12.vote.VoteResponseB\tZ\a../voteb\x06proto3"

var (
	file_vote_message_proto_rawDescOnce sync.Once
	file_vote_message_proto_rawDescData []byte
)

func file_vote_message_proto_rawDescGZIP() []byte {
	file_vote_message_proto_rawDescOnce.Do(func() {
		file_vote_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_message_proto_rawDesc), len(file_vote_message_proto_rawDesc)))
	})
	return file_vote_message_proto_rawDescData
}

var file_vote_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vote_message_proto_goTypes = []any{
	(*VoteRequest)(nil),  // 0: vote.VoteRequest
	(*VoteResponse)(nil), // 1: vote.VoteResponse
}
var file_vote_message_proto_depIdxs = []int32{
	0, // 0: vote.BlockchainService.SubmitVote:input_type -> vote.VoteRequest
	1, // 1: vote.BlockchainService.SubmitVote:output_type -> vote.VoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vote_message_proto_init() }
func file_vote_message_proto_init() {
	if File_vote_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_message_proto_rawDesc), len(file_vote_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_message_proto_goTypes,
		DependencyIndexes: file_vote_message_proto_depIdxs,
		MessageInfos:      file_vote_message_proto_msgTypes,
	}.Build()
	File_vote_message_proto = out.File
	file_vote_message_proto_goTypes = nil
	file_vote_message_proto_depIdxs = nil
}
