// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: vote_proposal_message.proto

package vote_proposal_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenProposalPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProposalPendingRequest) Reset() {
	*x = OpenProposalPendingRequest{}
	mi := &file_vote_proposal_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProposalPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProposalPendingRequest) ProtoMessage() {}

func (x *OpenProposalPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vote_proposal_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProposalPendingRequest.ProtoReflect.Descriptor instead.
func (*OpenProposalPendingRequest) Descriptor() ([]byte, []int) {
	return file_vote_proposal_message_proto_rawDescGZIP(), []int{0}
}

func (x *OpenProposalPendingRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *OpenProposalPendingRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type OpenProposalPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProposalPendingResponse) Reset() {
	*x = OpenProposalPendingResponse{}
	mi := &file_vote_proposal_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProposalPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProposalPendingResponse) ProtoMessage() {}

func (x *OpenProposalPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vote_proposal_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProposalPendingResponse.ProtoReflect.Descriptor instead.
func (*OpenProposalPendingResponse) Descriptor() ([]byte, []int) {
	return file_vote_proposal_message_proto_rawDescGZIP(), []int{1}
}

func (x *OpenProposalPendingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpenProposalPendingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OpenProposalPendingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_vote_proposal_message_proto protoreflect.FileDescriptor

const file_vote_proposal_message_proto_rawDesc = "" +
	"\n" +
	"\x1bvote_proposal_message.proto\x12\x15vote_proposal_message\"N\n" +
	"\x1aOpenProposalPendingRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"i\n" +
	"\x1bOpenProposalPendingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\x9d\x01\n" +
	"\x1dBlockchainVoteProposalService\x12|\n" +
	"\x13OpenProposalPending\x121.vote_proposal_message.OpenProposalPendingRequest\x1a2.vote_proposal_message.OpenProposalPendingResponseB'Z%../network/gRPC/vote_proposal_messageb\x06proto3"

var (
	file_vote_proposal_message_proto_rawDescOnce sync.Once
	file_vote_proposal_message_proto_rawDescData []byte
)

func file_vote_proposal_message_proto_rawDescGZIP() []byte {
	file_vote_proposal_message_proto_rawDescOnce.Do(func() {
		file_vote_proposal_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_proposal_message_proto_rawDesc), len(file_vote_proposal_message_proto_rawDesc)))
	})
	return file_vote_proposal_message_proto_rawDescData
}

var file_vote_proposal_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vote_proposal_message_proto_goTypes = []any{
	(*OpenProposalPendingRequest)(nil),  // 0: vote_proposal_message.OpenProposalPendingRequest
	(*OpenProposalPendingResponse)(nil), // 1: vote_proposal_message.OpenProposalPendingResponse
}
var file_vote_proposal_message_proto_depIdxs = []int32{
	0, // 0: vote_proposal_message.BlockchainVoteProposalService.OpenProposalPending:input_type -> vote_proposal_message.OpenProposalPendingRequest
	1, // 1: vote_proposal_message.BlockchainVoteProposalService.OpenProposalPending:output_type -> vote_proposal_message.OpenProposalPendingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vote_proposal_message_proto_init() }
func file_vote_proposal_message_proto_init() {
	if File_vote_proposal_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_proposal_message_proto_rawDesc), len(file_vote_proposal_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_proposal_message_proto_goTypes,
		DependencyIndexes: file_vote_proposal_message_proto_depIdxs,
		MessageInfos:      file_vote_proposal_message_proto_msgTypes,
	}.Build()
	File_vote_proposal_message_proto = out.File
	file_vote_proposal_message_proto_goTypes = nil
	file_vote_proposal_message_proto_depIdxs = nil
}
