// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: vote_proposal_message.proto

package vote_proposal_message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainVoteProposalService_OpenProposalPending_FullMethodName = "/vote_proposal_message.BlockchainVoteProposalService/OpenProposalPending"
)

// BlockchainVoteProposalServiceClient is the client API for BlockchainVoteProposalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainVoteProposalServiceClient interface {
	OpenProposalPending(ctx context.Context, in *OpenProposalRequest, opts ...grpc.CallOption) (*OpenProposalResponse, error)
}

type blockchainVoteProposalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainVoteProposalServiceClient(cc grpc.ClientConnInterface) BlockchainVoteProposalServiceClient {
	return &blockchainVoteProposalServiceClient{cc}
}

func (c *blockchainVoteProposalServiceClient) OpenProposalPending(ctx context.Context, in *OpenProposalRequest, opts ...grpc.CallOption) (*OpenProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenProposalResponse)
	err := c.cc.Invoke(ctx, BlockchainVoteProposalService_OpenProposalPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainVoteProposalServiceServer is the server API for BlockchainVoteProposalService service.
// All implementations must embed UnimplementedBlockchainVoteProposalServiceServer
// for forward compatibility.
type BlockchainVoteProposalServiceServer interface {
	OpenProposalPending(context.Context, *OpenProposalRequest) (*OpenProposalResponse, error)
	mustEmbedUnimplementedBlockchainVoteProposalServiceServer()
}

// UnimplementedBlockchainVoteProposalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainVoteProposalServiceServer struct{}

func (UnimplementedBlockchainVoteProposalServiceServer) OpenProposalPending(context.Context, *OpenProposalRequest) (*OpenProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenProposalPending not implemented")
}
func (UnimplementedBlockchainVoteProposalServiceServer) mustEmbedUnimplementedBlockchainVoteProposalServiceServer() {
}
func (UnimplementedBlockchainVoteProposalServiceServer) testEmbeddedByValue() {}

// UnsafeBlockchainVoteProposalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainVoteProposalServiceServer will
// result in compilation errors.
type UnsafeBlockchainVoteProposalServiceServer interface {
	mustEmbedUnimplementedBlockchainVoteProposalServiceServer()
}

func RegisterBlockchainVoteProposalServiceServer(s grpc.ServiceRegistrar, srv BlockchainVoteProposalServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockchainVoteProposalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainVoteProposalService_ServiceDesc, srv)
}

func _BlockchainVoteProposalService_OpenProposalPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainVoteProposalServiceServer).OpenProposalPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainVoteProposalService_OpenProposalPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainVoteProposalServiceServer).OpenProposalPending(ctx, req.(*OpenProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainVoteProposalService_ServiceDesc is the grpc.ServiceDesc for BlockchainVoteProposalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainVoteProposalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vote_proposal_message.BlockchainVoteProposalService",
	HandlerType: (*BlockchainVoteProposalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenProposalPending",
			Handler:    _BlockchainVoteProposalService_OpenProposalPending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote_proposal_message.proto",
}
