// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: topic_message.proto

package topic_message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainTopicService_SubmitTopic_FullMethodName = "/topic_message.BlockchainTopicService/SubmitTopic"
)

// BlockchainTopicServiceClient is the client API for BlockchainTopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainTopicServiceClient interface {
	SubmitTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
}

type blockchainTopicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainTopicServiceClient(cc grpc.ClientConnInterface) BlockchainTopicServiceClient {
	return &blockchainTopicServiceClient{cc}
}

func (c *blockchainTopicServiceClient) SubmitTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, BlockchainTopicService_SubmitTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainTopicServiceServer is the server API for BlockchainTopicService service.
// All implementations must embed UnimplementedBlockchainTopicServiceServer
// for forward compatibility.
type BlockchainTopicServiceServer interface {
	SubmitTopic(context.Context, *TopicRequest) (*TopicResponse, error)
	mustEmbedUnimplementedBlockchainTopicServiceServer()
}

// UnimplementedBlockchainTopicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainTopicServiceServer struct{}

func (UnimplementedBlockchainTopicServiceServer) SubmitTopic(context.Context, *TopicRequest) (*TopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTopic not implemented")
}
func (UnimplementedBlockchainTopicServiceServer) mustEmbedUnimplementedBlockchainTopicServiceServer() {
}
func (UnimplementedBlockchainTopicServiceServer) testEmbeddedByValue() {}

// UnsafeBlockchainTopicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainTopicServiceServer will
// result in compilation errors.
type UnsafeBlockchainTopicServiceServer interface {
	mustEmbedUnimplementedBlockchainTopicServiceServer()
}

func RegisterBlockchainTopicServiceServer(s grpc.ServiceRegistrar, srv BlockchainTopicServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockchainTopicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainTopicService_ServiceDesc, srv)
}

func _BlockchainTopicService_SubmitTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainTopicServiceServer).SubmitTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainTopicService_SubmitTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainTopicServiceServer).SubmitTopic(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainTopicService_ServiceDesc is the grpc.ServiceDesc for BlockchainTopicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainTopicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "topic_message.BlockchainTopicService",
	HandlerType: (*BlockchainTopicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTopic",
			Handler:    _BlockchainTopicService_SubmitTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topic_message.proto",
}
