// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: topic_message.proto

package topic_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicRequest) Reset() {
	*x = TopicRequest{}
	mi := &file_topic_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicRequest) ProtoMessage() {}

func (x *TopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicRequest.ProtoReflect.Descriptor instead.
func (*TopicRequest) Descriptor() ([]byte, []int) {
	return file_topic_message_proto_rawDescGZIP(), []int{0}
}

func (x *TopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResponse) Reset() {
	*x = TopicResponse{}
	mi := &file_topic_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResponse) ProtoMessage() {}

func (x *TopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResponse.ProtoReflect.Descriptor instead.
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return file_topic_message_proto_rawDescGZIP(), []int{1}
}

func (x *TopicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_topic_message_proto protoreflect.FileDescriptor

const file_topic_message_proto_rawDesc = "" +
	"\n" +
	"\x13topic_message.proto\x12\rtopic_message\"@\n" +
	"\fTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"[\n" +
	"\rTopicResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2b\n" +
	"\x16BlockchainTopicService\x12H\n" +
	"\vSubmitTopic\x12\x1b.topic_message.TopicRequest\x1a\x1c.topic_message.TopicResponseB\x1fZ\x1d../network/gRPC/topic_messageb\x06proto3"

var (
	file_topic_message_proto_rawDescOnce sync.Once
	file_topic_message_proto_rawDescData []byte
)

func file_topic_message_proto_rawDescGZIP() []byte {
	file_topic_message_proto_rawDescOnce.Do(func() {
		file_topic_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_message_proto_rawDesc), len(file_topic_message_proto_rawDesc)))
	})
	return file_topic_message_proto_rawDescData
}

var file_topic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_topic_message_proto_goTypes = []any{
	(*TopicRequest)(nil),  // 0: topic_message.TopicRequest
	(*TopicResponse)(nil), // 1: topic_message.TopicResponse
}
var file_topic_message_proto_depIdxs = []int32{
	0, // 0: topic_message.BlockchainTopicService.SubmitTopic:input_type -> topic_message.TopicRequest
	1, // 1: topic_message.BlockchainTopicService.SubmitTopic:output_type -> topic_message.TopicResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_topic_message_proto_init() }
func file_topic_message_proto_init() {
	if File_topic_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_message_proto_rawDesc), len(file_topic_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topic_message_proto_goTypes,
		DependencyIndexes: file_topic_message_proto_depIdxs,
		MessageInfos:      file_topic_message_proto_msgTypes,
	}.Build()
	File_topic_message_proto = out.File
	file_topic_message_proto_goTypes = nil
	file_topic_message_proto_depIdxs = nil
}
