// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: admin_l4_commands.proto

package admin_commands_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L4HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4HealthCheckRequest) Reset() {
	*x = L4HealthCheckRequest{}
	mi := &file_admin_l4_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4HealthCheckRequest) ProtoMessage() {}

func (x *L4HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_l4_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*L4HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_admin_l4_commands_proto_rawDescGZIP(), []int{0}
}

func (x *L4HealthCheckRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type L4HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Pong          string                 `protobuf:"bytes,3,opt,name=pong,proto3" json:"pong,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports         []uint32               `protobuf:"varint,5,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4HealthCheckResponse) Reset() {
	*x = L4HealthCheckResponse{}
	mi := &file_admin_l4_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4HealthCheckResponse) ProtoMessage() {}

func (x *L4HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_l4_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*L4HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_admin_l4_commands_proto_rawDescGZIP(), []int{1}
}

func (x *L4HealthCheckResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *L4HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *L4HealthCheckResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

func (x *L4HealthCheckResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *L4HealthCheckResponse) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_admin_l4_commands_proto protoreflect.FileDescriptor

const file_admin_l4_commands_proto_rawDesc = "" +
	"\n" +
	"\x17admin_l4_commands.proto\x12\x11admin_L4_commands\"*\n" +
	"\x14L4HealthCheckRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x87\x01\n" +
	"\x15L4HealthCheckResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04pong\x18\x03 \x01(\tR\x04pong\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x14\n" +
	"\x05ports\x18\x05 \x03(\rR\x05ports2n\n" +
	"\n" +
	"L4Commands\x12`\n" +
	"\vCheckHealth\x12'.admin_L4_commands.L4HealthCheckRequest\x1a(.admin_L4_commands.L4HealthCheckResponseB(Z&../network/gRPC/admin_commands_messageb\x06proto3"

var (
	file_admin_l4_commands_proto_rawDescOnce sync.Once
	file_admin_l4_commands_proto_rawDescData []byte
)

func file_admin_l4_commands_proto_rawDescGZIP() []byte {
	file_admin_l4_commands_proto_rawDescOnce.Do(func() {
		file_admin_l4_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_l4_commands_proto_rawDesc), len(file_admin_l4_commands_proto_rawDesc)))
	})
	return file_admin_l4_commands_proto_rawDescData
}

var file_admin_l4_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_l4_commands_proto_goTypes = []any{
	(*L4HealthCheckRequest)(nil),  // 0: admin_L4_commands.L4HealthCheckRequest
	(*L4HealthCheckResponse)(nil), // 1: admin_L4_commands.L4HealthCheckResponse
}
var file_admin_l4_commands_proto_depIdxs = []int32{
	0, // 0: admin_L4_commands.L4Commands.CheckHealth:input_type -> admin_L4_commands.L4HealthCheckRequest
	1, // 1: admin_L4_commands.L4Commands.CheckHealth:output_type -> admin_L4_commands.L4HealthCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_l4_commands_proto_init() }
func file_admin_l4_commands_proto_init() {
	if File_admin_l4_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_l4_commands_proto_rawDesc), len(file_admin_l4_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_l4_commands_proto_goTypes,
		DependencyIndexes: file_admin_l4_commands_proto_depIdxs,
		MessageInfos:      file_admin_l4_commands_proto_msgTypes,
	}.Build()
	File_admin_l4_commands_proto = out.File
	file_admin_l4_commands_proto_goTypes = nil
	file_admin_l4_commands_proto_depIdxs = nil
}
