// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: vote_message.proto

package vote_message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainVoteService_SubmitVote_FullMethodName = "/vote_message.BlockchainVoteService/SubmitVote"
)

// BlockchainVoteServiceClient is the client API for BlockchainVoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainVoteServiceClient interface {
	SubmitVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type blockchainVoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainVoteServiceClient(cc grpc.ClientConnInterface) BlockchainVoteServiceClient {
	return &blockchainVoteServiceClient{cc}
}

func (c *blockchainVoteServiceClient) SubmitVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, BlockchainVoteService_SubmitVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainVoteServiceServer is the server API for BlockchainVoteService service.
// All implementations must embed UnimplementedBlockchainVoteServiceServer
// for forward compatibility.
type BlockchainVoteServiceServer interface {
	SubmitVote(context.Context, *VoteRequest) (*VoteResponse, error)
	mustEmbedUnimplementedBlockchainVoteServiceServer()
}

// UnimplementedBlockchainVoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainVoteServiceServer struct{}

func (UnimplementedBlockchainVoteServiceServer) SubmitVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVote not implemented")
}
func (UnimplementedBlockchainVoteServiceServer) mustEmbedUnimplementedBlockchainVoteServiceServer() {}
func (UnimplementedBlockchainVoteServiceServer) testEmbeddedByValue()                               {}

// UnsafeBlockchainVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainVoteServiceServer will
// result in compilation errors.
type UnsafeBlockchainVoteServiceServer interface {
	mustEmbedUnimplementedBlockchainVoteServiceServer()
}

func RegisterBlockchainVoteServiceServer(s grpc.ServiceRegistrar, srv BlockchainVoteServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockchainVoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainVoteService_ServiceDesc, srv)
}

func _BlockchainVoteService_SubmitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainVoteServiceServer).SubmitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainVoteService_SubmitVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainVoteServiceServer).SubmitVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainVoteService_ServiceDesc is the grpc.ServiceDesc for BlockchainVoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainVoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vote_message.BlockchainVoteService",
	HandlerType: (*BlockchainVoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVote",
			Handler:    _BlockchainVoteService_SubmitVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote_message.proto",
}
